### ISSUE TITLE
hiprtTransformHeader 

### ISSUE THREAD

**Issue by ib00** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#17]
Is there any more detailed documentation on "hipTransformHeader"?

**Comment by PixelClear** [comment]
you can find more info in this sample -> https://github.com/GPUOpen-LibrariesAndSDKs/HIPRTSDK/blob/853935bdbe9d4538bd85decb999187e4124972c0/tutorials/07_motion_blur_srt/main.cpp#L146

If you need any further clarification please tell us. I will be more than happy to provide it.

**Comment by ib00** [comment]
The documentation says that 'hiprtTransformHeader' defines "index to the array of frames and the number of frames."

Traditionally, you would provide an array of transforms and time associated with that transform to then compute
the transform. Is this similar?

In the above example, you have 5 transforms that you are splitting into a group of 2 (3 + 2). What do these mean conceptually? Transformations for each instance where the first instance has 3 SRTs over time (t_start, t_end)?

**Comment by PixelClear** [comment]
There are two instances 

instance 0 -> 3 SRT frames associated with it
                      1st SRTframe.time -> t_start similarly 3rd SRTframe.time ->t_end
instance 1-> 2 SRT frames associated with it
                     1st SRTframe.time -> t_start similarly 2nd SRTframe.time ->t_end

So you are right conceptually it means first instance has 3SRTs over time and second instance has 2.
