### ISSUE TITLE
Q: Traversal questions

### ISSUE THREAD

**Issue by ib00** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#22]
I have two traversal questions:

1. This is a low level implementation detail. If there are multiple user-defined primitives in the scene, are there any optimizations to perform intersection of same primitives together? Or you essentially perform single intersection per warp?

2. Does the current API allow for "traversal shaders" with multiple levels of detail, something like this:
https://gpuopen.com/learn/why-multi-resolution-geometric-representation-bvh-ray-tracing/

Thanks!

**Comment by meistdan** [comment]
I am not sure if I understand the questions, either of them, but I will try to answer.
1. I guess the answer is no. There is no any internal grouping of the same geometry to decrease the warp divergence. In general rays are processed independently. What you can do is to use the warp-level primitives (e.g., `__ballot`) to communicate with other threads in the custom intersection function.
2. There is no any explicit support for LOD at the moment.

**Comment by ib00** [comment]
Thanks.
