### ISSUE TITLE
Linux support and requirements

### ISSUE THREAD

**Issue by FilipVaverka** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#3]
What system configurations are supported when running HIPRT on Linux?
I managed to build tutorials with few minor tweaks with GCC-11 (GCC-12 had some more issues) against ROCm-5.1.0 with upstream kernel components (OpenSUSE Linux 5.17.9-1-default) on Radeon VII (gfx906). While most tutorials seem to produce reasonably looking output images some of them crash somewhere in "libhsa-runtime64.so" after doing so:
> Reading symbols from ./bin/Debug/02_scene_intersection64D...
(gdb) r
Starting program: /home/Deluxe/Development/extern_projects/HIPRTSDK/tutorials/dist/bin/Debug/02_scene_intersection64D 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.35-3.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffeebff640 (LWP 24303)]
executing on AMD Radeon VII
[New Thread 0x7fffe6fff640 (LWP 24304)]
[Thread 0x7fffe6fff640 (LWP 24304) exited]
[New Thread 0x7ffff68c7640 (LWP 24305)]
>
> Thread 4 "02_scene_inters" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff68c7640 (LWP 24305)]
0x00007fffeecc38cf in ?? () from /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1
Missing separate debuginfos, use: zypper install comgr-debuginfo-2.4.0.50100-sles153.36.x86_64 hip-runtime-amd-debuginfo-5.1.20531.50100-sles153.36.x86_64 hsa-rocr-debuginfo-1.5.0.50100-sles153.36.x86_64 libdrm2-debuginfo-2.4.110-1.2.x86_64 libdrm_amdgpu1-debuginfo-2.4.110-1.2.x86_64 libelf1-debuginfo-0.187-3.1.x86_64 libgcc_s1-debuginfo-12.1.1+git78-25.1.x86_64 libncurses6-debuginfo-6.3.20220501-18.2.x86_64 libnuma1-debuginfo-2.0.14.39.g8b18345-1.1.x86_64 libstdc++6-debuginfo-12.1.0+git27-1.3.x86_64 libz1-debuginfo-1.2.11-19.4.x86_64
(gdb) bt
#0  0x00007fffeecc38cf in ?? ()
   from /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1
#1  0x00007fffeecc3f99 in ?? ()
   from /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1
#2  0x00007fffeec4cc42 in ?? ()
   from /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1
#3  0x00007fffeec4ca9a in ?? ()
   from /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1
#4  0x00007fffeec40a69 in ?? ()
   from /opt/rocm/hip/lib/../../lib/libhsa-runtime64.so.1
#5  0x00007ffff6c725dc in ?? () from /opt/rocm/hip/lib/libamdhip64.so
#6  0x00007ffff6a4ae96 in ?? () from /opt/rocm/hip/lib/libamdhip64.so
#7  0x00007ffff6c2331f in ?? () from /opt/rocm/hip/lib/libamdhip64.so
#8  0x00007ffff7a16767 in start_thread () from /lib64/libc.so.6
#9  0x00007ffff7aa0c10 in clone3 () from /lib64/libc.so.6

Tutorials 4 and 5 produce very bright images (compared to Windows):
![04_shared_stack](https://user-images.githubusercontent.com/10695212/169717263-0418c4d7-9fcc-4d75-9a2f-1f30a9b91344.png)
![05_custom_bvh_import](https://user-images.githubusercontent.com/10695212/169717274-757dc61c-0c26-4be7-8900-c1a8faf041db.png)

**Comment by PixelClear** [comment]
We have fixed this issue and have updated the SDK. Please try to run updated tutorials.
