### ISSUE TITLE
HIPRTC_ERROR_LINKING runtime error from hiprtBuildTraceKernelsFromBitcode

### ISSUE THREAD

**Issue by TomClabault** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#30]
I cloned the repo and downloaded the HIP RT binaries at https://gpuopen.com/hiprt/ and copied the 'hiprt' and 'contrib/Orochi' folders to the HIPRTSDK cloned repo folder. I ran the premake, opened the Visual Studio solution, compiled and ran the second tutorial 02_scene_intersection. However, I'm getting an HIPRTC_ERROR_LINKING error at runtime, caused by the hiprtBuildTraceKernelsFromBitcode function call in TutorialBase.cpp:232.

I'm running Windows 11 22H2 with a 7900XTX, Adrenalin drivers version 23.30.13.05 and Visual Studio Community 2022 17.8.3.

Here's the output of running 02_scene_intersection on my setup:

![TomClabault_0-1704276396369](https://github.com/GPUOpen-LibrariesAndSDKs/HIPRTSDK/assets/61839853/3742b155-3b91-4845-a05d-09e8e085de62)

All tutorials fail with the same error except 00_context_creation and 17_hiprt_hip,.

**Comment by RichardGe** [comment]
Hi, before investigating further, Could you try again with 23.12.1.
I'm asking that because from the  https://www.amd.com/en/support , I see that 23.12.1 is the latest recommended driver for the  7900XTX.

**Comment by RichardGe** [comment]
Hi, I'm not reproducing your issue on my side. 
I need to think how I can help you to debug that. In the meantime, could you confirm me that you don't have any environment variables modifying the HIP behavior.  those variables usually starts with HIP_......

**Comment by TomClabault** [comment]
Hi, I removed some HIP_PATH and ROCM_PATH environment variables I had installed (probably due to the installation of the [HIP SDK](https://www.amd.com/fr/developer/resources/rocm-hub/hip-sdk.html)). Still the same issue.

I uninstalled my HIP SDK, restarted my machine, cloned the repo again, download the binaries, compiled and ran but no changes, the issue is still here.

What can I try next?

**Comment by meistdan** [comment]
Hello, could you please try one thing? In `tutorials\dist\bin\Release\`, make a copy of `amd_comgr0507.dll` and rename it to `amd_comgr.dll`.

**Comment by TomClabault** [comment]
Hi meistdan,

Replacing the DLLs by those from the HIP SDK 5.7 seems to be working. Every tutorials run without runtime errors.

What is happenning? I'm trying to understand what was happening. I assume the DLLs from the binaries [https://gpuopen.com/hiprt/](https://gpuopen.com/hiprt/) are incorrect but in how so? How did you get the idea to replace the DLLs?

**Comment by meistdan** [comment]
I think this was due to a bug in 5.7 dlls, which incorrectly loads `amd_comgr.dll` instead of `amd_comgr0507.dll`.
