### ISSUE TITLE
[Question] Any hopes getting Hardware-accelerated ray tracing work on Nvidia GPUS?

### ISSUE THREAD

**Issue by trsh** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#31]

**Comment by ib00** [comment]
Does HIPRT use hardware acceleration on AMD GPUs?

**Comment by meistdan** [comment]
Sorry for the late reply.
@trsh I think this is not possible as NVIDIA RT functionality is not exposed.
@ib00 Yes, HIPRT uses HW acceleration on RDNA 2 and RDNA 3.
