### ISSUE TITLE
Compiler support (gcc-12 and clang-14)

### ISSUE THREAD

**Issue by FilipVaverka** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#4]
There are few minor complains from GCC 12 and Clang 14 compilers on Linux:
- Both GCC and Clang require comparison ```operator<``` on ```tinyobj::index_t``` in ```TestBase.cpp``` to be placed in ```tinyobj``` namespace instead of ```std```.
- Clang-14 also complains about narrowing floating point expressions in e.g. ```02_scene_intersection``` vertex array definition. This can be solved by using trig. functions from ```std``` namespace instead (as these are generic).

Here is git patch, which fixes these issues and allows me to compile the SDK with GCC-11, GCC-12 and Clang-14 (not tested under Windows): [compiler_gcc12_clang14.txt](https://github.com/GPUOpen-LibrariesAndSDKs/HIPRTSDK/files/9173675/compiler_gcc12_clang14.txt)

**Comment by PixelClear** [comment]
Hey thanks,
We have added these changes. You can take the latest tutorials and try them. 
Sorry, it took a bit long as we were in some priority releases.

**Comment by FilipVaverka** [comment]
Thanks, seems to compile and work fine with GCC 12.1.1 and 14.0.6.
