### ISSUE TITLE
Native ROCm/HIP integration

### ISSUE THREAD

**Issue by FilipVaverka** [GPUOpen-LibrariesAndSDKs/HIPRTSDK#9]
Is it possible to integrate HIPRT into native HIP/ROCm project without using Orochi?
It seems to me like this would be necessary to enable integration of HIPRT into various runtimes built upon native HIP (such as hipSYCL).

**Comment by PixelClear** [comment]
We are working on writing a tutorial for HIP-HIPRT (Non - Orochi) setup. We will update you soon!

**Comment by takahiroharada** [comment]
Please see this tutorial to use hiprt and hip. https://github.com/GPUOpen-LibrariesAndSDKs/HIPRTSDK/tree/main/tutorials/09-hiprt-hip
